@output_buffeer.safe_append = "<div>"

@output_buffer.safe_append='\n<ul class=\"list-group\">\n'.freeze;
@paths.each do |path| 
  \n
  @output_buffer.safe_append=' <li class=\"list-group-item\">\n'.freeze; 
  part_of_path_mapped_to_identity_global_path = path.split('/').each.with_index.inject({}) do |acc, (part_of_path, i)| 
    \n 
      acc[i] = part_of_path \n acc[part_of_path] = File.join('/' + path.file_system.machine_readable_identifier + '/', path.split('/').take(i + 1).join('/')) \n acc \n end \n@output_buffer.safe_append='\n'.freeze; if path.file_system.machine_readable_identifier == 'dropbox' \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to 'dropbox', root_path );@output_buffer.safe_append='\n'.freeze; else \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to 'local', root_path );@output_buffer.safe_append='\n'.freeze; end \n@output_buffer.safe_append='\n'.freeze; path.split('/').reject(&:blank?).each do |part_of_path| \n@output_buffer.safe_append=' <SPAN>/</SPAN> \n\n'.freeze; if path.file? && path.to_s =~ /.*?\#{Regexp.escape(part_of_path)}\\Z/ \n@output_buffer.safe_append=' <span style=\"color: purple\">'.freeze;@output_buffer.append=( path.split('/').last );@output_buffer.safe_append='</span>\n'.freeze; else \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to(part_of_path, directory_path(part_of_path_mapped_to_identity_global_path[part_of_path])) );@output_buffer.safe_append='\n'.freeze; end \n end \n@output_buffer.safe_append='\n\n'.freeze;\n\n\n\n\n@output_buffer.safe_append='\n\n\n'.freeze; if path.modified_at.present? \n@output_buffer.safe_append=' was modified\n '.freeze;@output_buffer.append=( time_ago_in_words(path.modified_at) );@output_buffer.safe_append='\n'.freeze; end \n if path =~ /\\.zip\\Z/ \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( button_to('Unzip', unzips_path(unzip: {zip_file_path: path.global_path})) );@output_buffer.safe_append='\n'.freeze; end \n@output_buffer.safe_append='\n'.freeze; if path.file? \n case File.extname(path.file_system_path) \n when '.shp' \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to 'View', ezii_os_file_path(path.global_path) );@output_buffer.safe_append='\n'.freeze; when '.xlsx' \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to 'View', ezii_os_file_path(path.global_path) );@output_buffer.safe_append='\n'.freeze; when '.pdf' \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to 'View', ezii_os_file_path(path.global_path) );@output_buffer.safe_append='\n'.freeze; when '.jpg' \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to 'View', ezii_os_file_path(path.global_path) );@output_buffer.safe_append='\n'.freeze; when '.erb' \n@output_buffer.safe_append=' '.freeze;@output_buffer.append=( link_to('Show INLINE (admin only)', ezii_os_file_path(path.global_path, admin: true)) );@output_buffer.safe_append='\n'.freeze; end \n end \n@output_buffer.safe_append=' </li>\n'.freeze; end \n@output_buffer.safe_append='</ul>'.freeze;\n@output_buffer.to_s
      
      


@output_buffeer.safe_append = "</div>"
